In [ ]:
#Develop model KNN using tensorflow

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [5]:
#Load data
df = pd.read_csv('C:\Bangkit ML 2024\Stunting\data_balita.csv')
data.head()

Umur (bulan) Jenis Kelamin  Tinggi Badan (cm)       Status Gizi
0             0     laki-laki          44.591973           stunted
1             0     laki-laki          56.705203            tinggi
2             0     laki-laki          46.863358            normal
3             0     laki-laki          47.508026            normal
4             0     laki-laki          42.743494  severely stunted

In [6]:
category_counts = df['Status Gizi'].value_counts()
category_counts

Status Gizi
normal              67755
severely stunted    19869
tinggi              19560
stunted             13815
Name: count, dtype: int64

In [7]:
# mengkodekan jenis kelamin
df['Jenis Kelamin'] = df['Jenis Kelamin'].map({'laki-laki': 0, 'perempuan': 1})

# mengkodekan status gizi
df['Status Gizi'] = df['Status Gizi'].map({'severely stunted': 0, 'stunted': 1, 'normal': 2, 'tinggi': 3})
df

Umur (bulan)  Jenis Kelamin  Tinggi Badan (cm)  Status Gizi
0                  0              0          44.591973            1
1                  0              0          56.705203            3
2                  0              0          46.863358            2
3                  0              0          47.508026            2
4                  0              0          42.743494            0
...              ...            ...                ...          ...
120994            60              1         100.600000            2
120995            60              1          98.300000            1
120996            60              1         121.300000            2
120997            60              1         112.200000            2
120998            60              1         109.800000            2

[120999 rows x 4 columns]

In [12]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

# Misalkan df adalah DataFrame yang sudah Anda miliki
# Misalkan fitur berada pada kolom 1 hingga 5 dan target pada kolom 'Status Gizi'

# Memisahkan fitur dan target
X = df.drop('Status Gizi', axis=1)
y = df['Status Gizi']

# Membagi dataset menjadi data latih dan data uji menggunakan scikit-learn
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Mengonversi data ke TensorFlow Dataset
train_dataset = tf.data.Dataset.from_tensor_slices((X_train.values, y_train.values))
test_dataset = tf.data.Dataset.from_tensor_slices((X_test.values, y_test.values))

# Mengatur batching dan shuffling pada dataset
BATCH_SIZE = 32
SHUFFLE_BUFFER_SIZE = 100

train_dataset = train_dataset.shuffle(SHUFFLE_BUFFER_SIZE).batch(BATCH_SIZE)
test_dataset = test_dataset.batch(BATCH_SIZE)

# Memeriksa salah satu batch dari train_dataset
for features, labels in train_dataset.take(1):
    print(features)
    print(labels)


tf.Tensor(
[[ 17.    0.   89.4]
 [ 59.    1.  106.3]
 [  5.    0.   59.2]
 [ 44.    1.   99. ]
 [  5.    1.   52.3]
 [ 35.    0.   92.6]
 [ 30.    1.   92.5]
 [ 31.    1.  103.7]
 [ 45.    1.   99. ]
 [ 20.    1.   83.8]
 [ 32.    1.   90.7]
 [ 58.    1.  120.4]
 [  6.    0.   54.5]
 [ 33.    0.  108.5]
 [  5.    1.   66.1]
 [ 57.    1.  122.7]
 [ 37.    0.   81.9]
 [ 55.    1.  105.5]
 [ 48.    1.   86.5]
 [ 23.    0.   98.7]
 [ 53.    0.  112.8]
 [ 54.    1.  123.6]
 [ 45.    0.   92.8]
 [ 14.    0.   65.6]
 [ 22.    1.   74.6]
 [  4.    0.   72.3]
 [ 34.    0.  108.6]
 [ 56.    1.   94.1]
 [ 11.    0.   64. ]
 [ 46.    1.   88.6]
 [ 36.    0.   91.3]
 [ 17.    0.   86.5]], shape=(32, 3), dtype=float64)
tf.Tensor([3 2 0 2 0 2 2 3 2 2 2 2 0 3 2 3 0 2 0 3 2 3 1 0 0 3 3 1 0 0 2 2], shape=(32,), dtype=int64)


In [13]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(5,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(4, activation='softmax')
])

model.compile(optimizer='adam',
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])

model.fit(train_dataset, epochs=10)

Epoch 1/10


C:\Users\Hafiz\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense" is incompatible with the layer: expected axis -1 of input shape to have value 5, but received input with shape (None, 3)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 3), dtype=float32)
  • training=True
  • mask=None

In [11]:
batch_size = 5
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)