In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
# membaca dataset dari file CSV
df = pd.read_csv('C:\Bangkit ML 2024\Stunting\data_balita.csv')
df

Umur (bulan) Jenis Kelamin  Tinggi Badan (cm)       Status Gizi
0                  0     laki-laki          44.591973           stunted
1                  0     laki-laki          56.705203            tinggi
2                  0     laki-laki          46.863358            normal
3                  0     laki-laki          47.508026            normal
4                  0     laki-laki          42.743494  severely stunted
...              ...           ...                ...               ...
120994            60     perempuan         100.600000            normal
120995            60     perempuan          98.300000           stunted
120996            60     perempuan         121.300000            normal
120997            60     perempuan         112.200000            normal
120998            60     perempuan         109.800000            normal

[120999 rows x 4 columns]

In [5]:
category_counts = df['Status Gizi'].value_counts()
category_counts

Status Gizi
normal              67755
severely stunted    19869
tinggi              19560
stunted             13815
Name: count, dtype: int64

In [6]:
# mengkodekan jenis kelamin
df['Jenis Kelamin'] = df['Jenis Kelamin'].map({'laki-laki': 0, 'perempuan': 1})

# mengkodekan status gizi
df['Status Gizi'] = df['Status Gizi'].map({'severely stunted': 0, 'stunted': 1, 'normal': 2, 'tinggi': 3})
df

Umur (bulan)  Jenis Kelamin  Tinggi Badan (cm)  Status Gizi
0                  0              0          44.591973            1
1                  0              0          56.705203            3
2                  0              0          46.863358            2
3                  0              0          47.508026            2
4                  0              0          42.743494            0
...              ...            ...                ...          ...
120994            60              1         100.600000            2
120995            60              1          98.300000            1
120996            60              1         121.300000            2
120997            60              1         112.200000            2
120998            60              1         109.800000            2

[120999 rows x 4 columns]

In [1]:
from sklearn.model_selection import train_test_split

# memisahkan fitur dan target
X = df.iloc[:, 1:6]
X = df.drop('Status Gizi', axis=1)
y = df['Status Gizi']

# membagi dataset menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X

NameError: name 'df' is not defined

In [2]:
import tensorflow as tf

# Define the model
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(1, input_shape=(X_train.shape[1],), activation='sigmoid')
])

# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print('Test accuracy:', accuracy)

NameError: name 'X_train' is not defined

In [10]:
from sklearn.metrics import accuracy_score
# Make predictions with the Logistic Regression model
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the accuracy of the Logistic Regression model
accuracy = accuracy_score(y_test, y_pred)
print('Test accuracy:', accuracy)

757/757 ━━━━━━━━━━━━━━━━━━━━ 1s 889us/step
Test accuracy: 0.11528925619834711


In [11]:
from sklearn.metrics import confusion_matrix

# Make predictions with the Logistic Regression model
y_pred_probs = model.predict(X_test)
y_pred = (y_pred_probs > 0.5).astype(int)

# Calculate the confusion matrix of the Logistic Regression model
confusion = confusion_matrix(y_test, y_pred)
print('Confusion matrix for Logistic Regression model:\n', confusion)

757/757 ━━━━━━━━━━━━━━━━━━━━ 0s 514us/step
Confusion matrix for Logistic Regression model:
 [[    0  4130     0     0]
 [    0  2790     0     0]
 [    0 13382     0     0]
 [    0  3898     0     0]]


In [12]:
print(classification_report(y_test.values.reshape(-1, 1), y_pred))

NameError: name 'classification_report' is not defined

In [13]:
from sklearn.model_selection import cross_val_score

print('Cross val: ', cross_val_score(knn, y_test.values.reshape(-1, 1), y_pred, cv = 5))
print('Accuracy : ', np.mean(cross_val_score(knn, y_test.values.reshape(-1, 1), y_pred)))

NameError: name 'knn' is not defined

In [11]:
# Testing model
test = pd.DataFrame({'Umur (bulan)': [20], 'Jenis Kelamin': [1], 'Tinggi Badan (cm)': [86.2]})

pred = knn.predict(test)
print("Predicted Score = {}".format(np.array(pred)))

Predicted Score = [2]


In [12]:
# Export the model
import joblib

joblib.dump(knn, 'knn.model')

['knn.model']